/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.main.GUI;

import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class StartPage extends javax.swing.JFrame {



    /**
     * Creates new form GamePage
     */
    public StartPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        btnsignup = new javax.swing.JButton();
        btnshowLb = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        leaderBoard = new javax.swing.JTable();
        bitnsignin1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 195, -1, -1));
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 420, 530));

        jLabel6.setFont(new java.awt.Font("Segoe Script", 1, 60)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 153));
        jLabel6.setText("E");
        jLabel6.setMaximumSize(new java.awt.Dimension(50, 66));
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 60, 60));

        jLabel7.setFont(new java.awt.Font("Segoe Script", 1, 60)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 153));
        jLabel7.setText("Q");
        jLabel7.setMaximumSize(new java.awt.Dimension(50, 66));
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 60));

        jLabel8.setFont(new java.awt.Font("Segoe Script", 1, 60)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 153));
        jLabel8.setText("U");
        jLabel8.setMaximumSize(new java.awt.Dimension(50, 66));
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, 60));

        jLabel9.setFont(new java.awt.Font("Segoe Script", 1, 60)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 153));
        jLabel9.setText("I");
        jLabel9.setMaximumSize(new java.awt.Dimension(50, 66));
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, 50));

        jLabel10.setFont(new java.awt.Font("Segoe Script", 1, 60)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 153));
        jLabel10.setText("Z");
        jLabel10.setMaximumSize(new java.awt.Dimension(50, 66));
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 60, 60));

        jLabel11.setFont(new java.awt.Font("Segoe Script", 1, 60)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 153));
        jLabel11.setText("G");
        jLabel11.setMaximumSize(new java.awt.Dimension(50, 66));
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 60, 60));

        jLabel12.setFont(new java.awt.Font("Segoe Script", 1, 60)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 153));
        jLabel12.setText("A");
        jLabel12.setMaximumSize(new java.awt.Dimension(50, 66));
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 60, 60));

        jLabel13.setFont(new java.awt.Font("Segoe Script", 1, 60)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 153));
        jLabel13.setText("M");
        jLabel13.setMaximumSize(new java.awt.Dimension(50, 66));
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 60, 60));

        jPanel2.setBackground(new java.awt.Color(0, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, -1, -1));

        btnsignup.setBackground(new java.awt.Color(0, 255, 255));
        btnsignup.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnsignup.setForeground(new java.awt.Color(0, 204, 204));
        btnsignup.setText("Exit");
        btnsignup.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 3));
        btnsignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsignupActionPerformed(evt);
            }
        });
        jPanel2.add(btnsignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 180, 60));

        btnshowLb.setBackground(new java.awt.Color(0, 255, 255));
        btnshowLb.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnshowLb.setForeground(new java.awt.Color(0, 204, 204));
        btnshowLb.setText("View");
        btnshowLb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 3));
        btnshowLb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnshowLbActionPerformed(evt);
            }
        });
        jPanel2.add(btnshowLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, 160, 60));

        jLabel5.setFont(new java.awt.Font("Stencil", 1, 60)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 204));
        jLabel5.setText("Leaderboard");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, -1, 80));

        leaderBoard.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Username", "score"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(leaderBoard);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, 220, 110));

        bitnsignin1.setBackground(new java.awt.Color(0, 255, 255));
        bitnsignin1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bitnsignin1.setForeground(new java.awt.Color(0, 204, 204));
        bitnsignin1.setText("Start Game");
        bitnsignin1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 3));
        bitnsignin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bitnsignin1ActionPerformed(evt);
            }
        });
        jPanel2.add(bitnsignin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 180, 60));

        jLabel14.setFont(new java.awt.Font("Stencil", 1, 60)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 204, 204));
        jLabel14.setText("START PAGE");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsignupActionPerformed
   
        dispose();
    }//GEN-LAST:event_btnsignupActionPerformed

    private void btnshowLbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnshowLbActionPerformed
       try {

            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/gameuser", "root", "");
                        Statement stmt = con.createStatement();


            String query = "SELECT * FROM signin ORDER by score DESC ";
            
             ResultSet rs = stmt.executeQuery(query);
             
             while(rs.next()){
                 String Username = rs.getString("Username");
                 String score =String.valueOf(rs.getInt("score"));
                 
                 String leaderBoardlb[]= {Username, score};
                    DefaultTableModel tblModel = (DefaultTableModel)leaderBoard.getModel();
                    tblModel.addRow(leaderBoardlb);
                    
                       
             System.out.println(Username); 
             System.out.println(score); 
             
             
             con.close();      
         
             }
        } catch (Exception e) {
            System. out.println(e);
            
        
       }                          
    
        
    }//GEN-LAST:event_btnshowLbActionPerformed

    private void bitnsignin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bitnsignin1ActionPerformed
          new GameInterface().setVisible(true);
          dispose();
    }//GEN-LAST:event_bitnsignin1ActionPerformed

public static void main(String args[]) {
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bitnsignin1;
    private javax.swing.JButton btnshowLb;
    private javax.swing.JButton btnsignup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable leaderBoard;
    // End of variables declaration//GEN-END:variables

    public ActionListener setVisible() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
